
default: exetarget

LIBS =	\
		-lcar \
		-lutil \
		-lboost_filesystem \
		-lboost_system \

SUBDIRS =

OBJS =	\
		testEDirection.o \
		testEOrientation.o \
		testCCar.o \

include $(RALLY_ROOT)/tst/tst.mk

