
default: exetarget

EXE=rally.exe

GRAPHLIBS =	\
			-lalleg-4.2.3 \
			-lalleg_unsharable \

LIBS =	\
		-lgameliballegro \
		-lgamelib \
		-lutil \
		$(GRAPHLIBS) \

SUBDIRS =

OBJS =	\
		rally.o \

include $(RALLY_ROOT)/src/src.mk

