
default: exetarget

EXE=rally.exe

GRAPHLIBS =	\
			-lalleg \

LIBS =	\
		-lgame \
		-lgameliballegro \
		-lgameliballegrobmp \
		-lgamelib \
		-lmap \
		-lutil \
		$(GRAPHLIBS) \
		-lboost_filesystem \
		-lboost_system \
		

SUBDIRS =

OBJS =	\
		rally.o \

include $(RALLY_ROOT)/src/src.mk

