version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:19.04
    steps:
      - checkout
      - run:
          name: Install tools
          command: sudo apt install -y g++-9 cmake cppcheck liballegro5-dev
      - run:
          name: Link to g++
          command: sudo rm -f /usr/bin/g++ && sudo ln -s /usr/bin/g++-9 /usr/bin/g++
      - run:
          name: Build system
          command: ./runbuild
      - run:
          name: Test system
          command: ./runbuild test
      - run:
          name: Cppcheck system
          command: ./runbuild check
