
default: exetarget

LIBS =	\
		-lmap \
		-lutil \
		-lboost_filesystem \
		-lboost_system \

SUBDIRS =

OBJS =	\
		testCMap.o \
		testCMapIO.o \
		testCTile.o \
		testETile.o \
		testEAction.o \

include $(RALLY_ROOT)/tst/tst.mk

