
default: exetarget

LIBS =	\
		-lmckgamelib \
		-lgame \
		-lgamelib \
		-lmap \
		-lutil \
		-lboost_filesystem \
		-lboost_system \

SUBDIRS =

OBJS =	\
		testCController.o \

include $(RALLY_ROOT)/tst/tst.mk

