
default: exetarget

EXE=map_editor.exe

GRAPHLIBS =	\
			-lalleg-4.2.3 \
			-lalleg_unsharable \

LIBS =	\
		-lgameliballegro \
		-lgamelib \
		-lutil \
		$(GRAPHLIBS) \

SUBDIRS =

OBJS =	\
		map_editor.o \

include $(RALLY_ROOT)/tools/tools.mk

